#!/bin/bash

# Define command-line arguments

RESOURCE_TYPE=$1
NAMESPACE=$2

print_header() {
    printf "%-15s %-15s %-40s %-10s %-10s\n" "Resource" "Namespace" "Name" "CPU" "Memory"
}

print_header

kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  print_row() {
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')
  printf "%-15s %-15s %-40s %-10s %-10s\n" "$RESOURCE_TYPE" "$NAMESPACE" "$NAME" "$CPU" "$MEMORY"
  }
  print_row
done
